### ISSUE TITLE
GitHub Actions started to fail, probably due to `delete_history: true` and growing archive size

### ISSUE THREAD

**Issue by i-ky** [zulip/zulip-archive#100]
I've started seeing consistent GitHub Actions failures recently:
```
error: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
```
Full log is available [here](https://github.com/OSMLatvija/zulip-archive/actions/runs/5007456514/jobs/8974090226).

It is an archive of a living Zulip organization, so it is constantly growing in size. I suspected the size simply got too big and overwriting the whole repo started to hit some kind of a limit. Therefore I tried to change action configuration to `delete_history: false` and the next run was a success.

I am filing this issue just to confirm, that there is a size limit for an archive, that can be published with GitHub Actions. Maybe there is a fix, maybe it simply needs to be documented.

**Comment by rht** [comment]
What is the size of your repo just before it failed? Maybe we can clarify in the documentation of the caveat if `delete_history: false`.

**Comment by i-ky** [comment]
I am not sure if my measurement methods can be trusted, but here is what I did:

This is repo state when `delete_history: true`:
https://github.com/OSMLatvija/zulip-archive/tree/d5ef2ce8ddb72f8c32d1358aa6605ff33022cdac

This is repo state after firsts successful workflow run with `delete_history: false`:
https://github.com/OSMLatvija/zulip-archive/tree/00435ccd78cb10bd8388e9b3aea17e3452fe5d04

I assume the latter is the same (module `true` -> `false` change in workflow settings) as repo state would be if it did not start to fail.

I downloaded both states as ZIP, unpacked and checked _Properties_ of both directories:
> 519 items, totalling 4,8 MB (5,8 MB on disk)

More precisely:
```
$ du zulip-archive-00435ccd78cb10bd8388e9b3aea17e3452fe5d04 zulip-archive-d5ef2ce8ddb72f8c32d1358aa6605ff33022cdac -s -b
5312956	zulip-archive-00435ccd78cb10bd8388e9b3aea17e3452fe5d04
5312954	zulip-archive-d5ef2ce8ddb72f8c32d1358aa6605ff33022cdac
```

I am a bit skeptical about these two bytes being the problem, but [who knows when non-heap becomes a heap](https://en.wikipedia.org/wiki/Sorites_paradox)...

**Comment by i-ky** [comment]
https://github.com/orgs/community/discussions/55820 has the same error mentioned.

**Comment by rht** [comment]
My mistake, I thought what you did was changing from `delete_history: false` to `delete_history: true`. I though having the entirety of the Git history makes it too big. I have observed the same persistent failures in https://github.com/JuliaCommunity/zulip-archive (cc @SaschaMann). I think we should do Git history pruning instead of the brute for `rm -rf .git && git init` (in https://github.com/zulip/zulip-archive/blob/42a52ec38b7ca29e5202af01d508d422ea2ddbb5/entrypoint.sh#L106-L112).

**Comment by rht** [comment]
[`git commit --amend`](https://github.com/rht/zulip-archive/commit/1b777b11c418a8050f2fc0c7ff01e8427019ac72) seemed to solve the problem: https://github.com/rht/zulip-archive-sample/actions/runs/5035853288. I'm debating over whether it should be the default behavior to prune to 1 commit, because most use cases concern only having the latest version of the archive.

**Comment by i-ky** [comment]
> I have observed the same persistent failures in https://github.com/JuliaCommunity/zulip-archive

Curiously, started to fail around same time as mine.

**Comment by kappelmann** [comment]
Our instance also started to fail a few days ago:
https://github.com/isabelle-prover/zulip-archive

**Comment by SaschaMann** [comment]
> I'm debating over whether it should be the default behavior to prune to 1 commit, because most use cases concern only having the latest version of the archive.

Code search suggests this would be non-breaking at least among public repos:

- `delete_history: true`: https://github.com/search?q=delete_history%3A+true+language%3AYAML+path%3A%2F%5E.github%5C%2Fworkflows%5C%2F%2F&type=code
- `delete_history: false`: https://github.com/search?q=delete_history%3A+false+language%3AYAML+path%3A%2F^.github\%2Fworkflows\%2F%2F&type=code

https://github.com/robertylewis/archive is the only hit which appears to be inactive.

**Comment by rht** [comment]
> Code search suggests this would be non-breaking at least among public repos:

The README.md actually recommends `delete_history: true`, so all is fine.
