### ISSUE TITLE
In permalink, stream id and stream name are not separated

### ISSUE THREAD

**Issue by rht** [zulip/zulip-archive#23]
E.g.
`permalink: archive/213222general`

with a stream id of `213222` and stream name of `general` may cause collision with a stream id of `21322` and stream name of `2general`.

See https://chat.zulip.org/#narrow/stream/127-integrations/topic/zulip-archive/near/804118 for further discussion.

**Comment by rht** [comment]
cc: @robertylewis

**Comment by robertylewis** [comment]
Indeed, it doesn't seem likely to come up non-maliciously, but it's an easy fix. If/when we move the Lean archive to a new format, we'd definitely want to set up redirects from the old format.
