### ISSUE TITLE
Broken css link

### ISSUE THREAD

**Issue by robertylewis** [zulip/zulip-archive#36]
See my comment here: https://github.com/zulip/zulip-archive/commit/01c1ac55ddc9e222c94dd2dbe71a5b288aefbc6e#commitcomment-38731915

There are relative CSS links on every topic page that (1) are redirected off-site by the base href change, and (2) wouldn't work anyway unless a copy of the CSS file appears in every subdirectory.

The CSS file that this links to only has a single line. Maybe this should all just be deleted?

**Comment by showell** [comment]
@robertylewis That code review comment appears to be for an older version of the code.  Have you tested this with a more recent version?

**Comment by robertylewis** [comment]
It's still there, in a different file: https://github.com/zulip/zulip-archive/blob/master/lib/jekyll.py#L207

View the source of e.g. https://leanprover-community.github.io/archive/stream/113488-general/topic/transitive.20coercions.html which is being generated with the latest version. It's a misplaced `<head>` with a link to a nonexistent https://leanprover.zulipchat.com/style.css

**Comment by Abhirup-99** [comment]
This issue is still there, have pushed a pr to fix this.
