### ISSUE TITLE
Directory structure is inconsistent

### ISSUE THREAD

**Issue by robertylewis** [zulip/zulip-archive#37]
The topic pages get stored at `/<stream-id>-<stream-name>/topic/<topic-name>.html`. The topic index pages get stored at `/stream/<stream-id>-<stream-name>/index.md`. (Notice the `stream/` at the beginning.) The topic pages are permalinked with a `stream/` at the beginning, so things work after Jekyll builds the full site, but this seems needlessly complicated.

Example: https://github.com/leanprover-community/archive (Ignore the top level directories without `-` after the IDs. Those are there to redirect from the old URL scheme.)

**Comment by refeed** [comment]
I think this has been fixed in the master branch, https://github.com/zulip/zulip-archive/blob/5da606feac0fa69445de717c406f79dd81e82e59/lib/url.py#L37-L52

**Comment by timabbott** [comment]
That looks right, closing.
