### ISSUE TITLE
Option to push updates without preserving history

### ISSUE THREAD

**Issue by robertylewis** [zulip/zulip-archive#38]
We've been using the GH Action version of the script for a couple months now, updating once an hour. The repo it pushes to is now 3.5gb, and the checkout step of the action takes 7 minutes. Storing the full history of the html/md files is usually not necessary. It would be great if the action had an option to force push, so that the repo size doesn't explode.

**Comment by maxandersen** [comment]
@robertylewis any plans for you to submit your fix as a  pull request?

**Comment by rht** [comment]
Can be closed. By #39

**Comment by maxandersen** [comment]
so i tried using this but I get:

```
Unexpected input(s) 'delete_history', valid inputs are ['entryPoint', 'args', 'zulip_organization_url', 'zulip_bot_email', 'zulip_bot_key', 'github_personal_access_token', 'archive_branch']
```

and delete_history seem to be deleted in https://github.com/zulip/zulip-archive/blob/master/action.yml in its last commit.

documentation does not match the code ...

**Comment by rht** [comment]
It works for me: https://github.com/rht/zulip-archive-sample/blob/main/.github/workflows/main.yml#L20.

**Comment by rht** [comment]
Another working example: https://github.com/JuliaCommunity/zulip-archive/blob/master/.github/workflows/deploy.yml.

**Comment by maxandersen** [comment]
Try build with a fresh catch? look at the action.yaml - it's missing declaration of delete history.

**Comment by maxandersen** [comment]
And @rht none of your examples uses this repos master version. 

Thus you aren't running the latest.

**Comment by rht** [comment]
My fork is ahead of upstream, which I use, see: https://github.com/rht/zulip-archive. And my modification has nothing to do with action.yml nor delete_history.

**Comment by rht** [comment]
I suppose GitHub has changed the action.yml specification so that unspecified arguments can't be passed implicitly.

**Comment by rht** [comment]
@maxandersen can you try if the branch in https://github.com/zulip/zulip-archive/pull/67 works?

**Comment by maxandersen** [comment]
its works.
