### ISSUE TITLE
Can't create github_personal_access_token

### ISSUE THREAD

**Issue by mateuszmandera** [zulip/zulip-archive#40]
When attempting to add a Secret `github_personal_access_token` the error `Failed to add secret. Name is invalid.` is returned. Has GitHub perhaps changed something recently that makes it impossible to use a secret with this kind of name now?

**Comment by hackerkid** [comment]
@mateuszmandera Yeah. Looks like GitHub don't allow prefixing the secret names with github_ anymore.

Can you try out the updated instructions in https://github.com/zulip/zulip-archive/pull/41/files?

**Comment by davidhe7** [comment]
Updated according to the instruction, now when I run actions, there's an error.

.github/workflows/main.yaml / A job to publish zulip-archive in GitHub pages

I have enabled Github pages, but got this error:

`Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.2-cp36-cp36m-linux_x86_64.whl size=44209 sha256=be33c8750cccf3949306250f792adf3f7522bcc671d310731208e1e15db3c36f
  Stored in directory: /tmp/pip-ephem-wheel-cache-iuy_5ivr/wheels/af/4b/a6/d492db4435642aebd1df1cd3ed075815e75ad6665aa47f4d04
Successfully built pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-5.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
100   145  100   132  100    13    814     80 --:--:-- --:--:-- --:--:--   895
  "message": "Problems parsing JSON",
  "documentation_url": "https://developer.github.com/v3/repos/pages/#enable-a-pages-site"
}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   135  100   135    0     0    944      0 --:--:-- --:--:-- --:--:--   944
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'html_url'`

**Comment by davidhe7** [comment]
This works!

Another question: I had to enable Github pages feature to use the action. But it seems that all Github pages must be public.

Is there anyway to have a private backup?

**Comment by hackerkid** [comment]
@davidhe7 I don't think there is a straightforward way to make a private archive using GitHub pages.

Another alternative is to run the tool on your own instead of using the GitHub action.  Details for that can be seen at 
 https://github.com/zulip/zulip-archive/blob/master/instructions.md
