### ISSUE TITLE
Apply Black to the entire repo

### ISSUE THREAD

**Issue by rht** [zulip/zulip-archive#60]
https://github.com/psf/black.
And then
- do Black check in CI
- Add Black badge like https://github.com/zulip/zulip does

**Comment by timabbott** [comment]
@rht I think all that's remaining is CI and badge, right?

(I suppose we could also setup `zulint`)

**Comment by rht** [comment]
Yes, CI and badge. I'm waiting for @neiljp to use `zulint` in ZT so that I can just clone their procedure here.
