### ISSUE TITLE
Automatically generate sitemap.xml after the archive is built.

### ISSUE THREAD

**Issue by rht** [zulip/zulip-archive#70]
https://www.jcchouinard.com/create-xml-sitemap-with-python/ has an example of doing it via jinja2 for templating the xml content.

**Comment by timabbott** [comment]
Just adding a link to the successful test here: https://chat.zulip.org/#narrow/stream/127-integrations/topic/zulip-archive/near/1257000.

**Comment by refeed** [comment]
I also think to add it to `robots.txt`'s sitemap field so that search engines can crawl through it
