### ISSUE TITLE
Allow use of GITHUB_TOKEN when running in GH Actions

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-archive#77]
Ideally this tool could run as a GitHub Action without the need to manage a personal access token (since scopes on personal tokens are coarse grained, and best practices keep them short lived).

Relevant bits:

* https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
* https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps#http-based-git-access-by-an-installation

**Comment by refeed** [comment]
I think the code already support the usage of `GITHUB_TOKEN`, I've already tested this on https://refeed.github.io/zarchive_refeed2/ , so we need to only change the documentation. Any thoughts @rht?

**Comment by rht** [comment]
Yeah, `GITHUB_TOKEN` will simplify the documentation.

**Comment by i-ky** [comment]
I have just configured a repo with:
```yaml
         github_personal_access_token: ${{ secrets.GITHUB_TOKEN }} 
```
I wish it was mentioned in README:
https://github.com/zulip/zulip-archive/blob/86efe95a59013eab1ab79cb8a4b5c223d14964bf/README.md?plain=1#L110
That could have saved some considerable time I wasted on reading GitHub documentation about various kinds of tokens, secrets, etc. and debugging access issues...

Please consider fast-tracking #90.

**Comment by rht** [comment]
#90 only needs https://github.com/zulip/zulip-archive/pull/90#discussion_r967700229 to be addressed.
