### ISSUE TITLE
instructions.md: dependency list is now incorrect

### ISSUE THREAD

**Issue by gasche** [zulip/zulip-archive#98]
`xml-sitemap-writer` was added as a dependency last August by https://github.com/zulip/zulip-archive/commit/980675c6bb268d7cd222aa84cdc11446de3ba99a , and it is not listed as a dependency in the current [instructions.md](https://github.com/zulip/zulip-archive/blob/697debb7eedcf2656e3da6197e84b008ea6c475a/instructions.md).

Note: Along with @Zimmi48 we maintain a Gitlab CI script to produce Zulip archives, similar to the Github actions, and this is how I noticed the issue. <https://gitlab.com/gasche/zulip-archive-gitlab-ci>.

I am trying to fix the issue in a more robust way by simply calling `pip` on the `requirements.txt` file. Maybe instructions.md could document this more robust workflow?

**Comment by rht** [comment]
Yeah, the instructions.md should have been updated to do `pip install -r requirements.txt`.

**Comment by rht** [comment]
Should be fixed by #99.

**Comment by gasche** [comment]
Apropos instructions.md: I found out the hard way a couple days ago that, on recent systems that respect [PEP 668](https://discuss.python.org/t/pep-668-marking-python-base-environments-as-externally-managed/10302/74) you now need to either setup a virtualenv first or pass `--break-system-packages`.

I think that this is mostly relevant for people writing archiving scripts in containers (where it is not common practice to setup a virtualenv), I would assume that direct users use a virtualenv already.

**Comment by rht** [comment]
Currently, the entrypoint.sh for the GH Actions uses virtualenv: https://github.com/zulip/zulip-archive/blob/697debb7eedcf2656e3da6197e84b008ea6c475a/entrypoint.sh#L43-L46. Maybe we should change it to the way you do it with no virtualenv:
```
pip3 install --user --break-system-packages -r zulip-archive/requirements.txt
```
Which saves ~15 MB in the container size.

But adding `--break-system-packages` to instructions.md would complicate it.
